from number_extract import *

def run_tests():
    
    test_cases = {
    
    # Nombres de base (0 à 100)
    "zero": "0",
    "zéro": "0",
    "aucun": "0%",
    "rien": "0%",
    "il y en a zero enfait": "0",
    "je veut rien": "0%",
    "je veut zero de ces trucs": "0",
    "il n y a rien dans cette phrase": "0%",
    "presque rien": "5%",
    "presque aucun": "5%",
    "un": "1",
    "un seul": "1",
    "deux": "2",
    "deux fois": "2",
    "trois": "3",
    "trois fois": "3",
    "quatre": "4",
    "cinq": "5",
    "six": "6",
    "sept": "7",
    "huit": "8",
    "neuf": "9",
    "dix": "10",
    "onze": "11",
    "douze": "12",
    "treize": "13",
    "quatorze": "14",
    "quinze": "15",
    "seize": "16",
    "dix-sept": "17",
    "dix-huit": "18",
    "il y en a dix et huit": "18",
    "dix-neuf": "19",
    "vingt": "20",
    "autour de vingt": "20",
    "vingt et un": "21",
    "vingt-et-un": "21",
    "il y en a vingt et un": "21",
    "vingt deux": "22",
    "vingt-et-deux": "22",
    "nous avons vingt deux ans": "22",
    "trente": "30",
    "trente et un": "31",
    "trente quatre": "34",
    "trente sept": "37",
    "quarante": "40",
    "quarente": "40",
    "quarante deux": "42",
    "quarante cinq": "45",
    "cinquante": "50",
    "cinquante neuf": "59",
    "soixante": "60",
    "soixante dix": "70",
    "septante": "70",
    "soixante et onze": "71",
    "soixante douze": "72",
    "soixante treize": "73",
    "septante quatre": "74",
    "soixante quatorze": "74",
    "soixante quinze": "75",
    "soixante seize": "76",
    "soixante-dix-neuf": "79",
    "quatre vingt": "80",
    "huitante": "80",
    "quatre vingt un": "81",
    "octante et un": "81",
    "quatre-vingt-un": "81",
    "quatre vingt huit": "88",
    "quatre vingt dix": "90",
    "nonante": "90",
    "quatre vingt onze": "91",
    "nonante deux": "92",
    "quatre vingt treize": "93",
    "quatre vingt quinze": "95",
    "quatre vingt dix-neuf": "99",
    "quatre-vingt-dix-neuf": "99",
    "cent": "100",
    "cent un": "101",
    "cent vingt": "120",
    "cent vingt trois": "123",
    "cent quarante huit": "148",
    "deux cent": "200",
    "deux cents": "200",
    "trois cent quarante cinq": "345",
    "cinq cent soixante sept": "567",
    "sept cent soixante quinze": "775",
    "dix-huit cent": "1800",
    "mille": "1000",
    "mille et un": "1001",
    "mille deux": "1002",
    "mille cent": "1100",
    "mille cent vingt trois": "1123",
    "mille deux cent trente quatre": "1234",
    "mille neuf cent quatre vingt quatre": "1984",
    "deux mille": "2000",
    "deux mille douze": "2012",
    "deux mille vingt et un": "2021",
    "deux mille vingt trois": "2023",
    "trois mille": "3000",
    "trois mille cent": "3100",
    "trois mille trois cent trente trois": "3333",
    "quatre mille": "4000",
    "quatre mille cent vingt trois": "4123",
    "quatre mille quatre cent quarante quatre": "4444",
    "cinq mille cent un": "5101",
    "cinq mille cent vingt trois": "5123",
    "cinq mille cinq cent cinquante cinq": "5555",
    "six mille six cent soixante six": "6666",
    "sept mille sept cent soixante six": "7766",
    "sept mille huit cent soixante dix": "7870",
    "huit mille huit cent quatre vingt huit": "8888",
    "neuf mille neuf cent quatre vingt neuf": "9989",
    "dix mille": "10000",
    "dix mille cent": "10100",
    "dix mille deux cent trente quatre": "10234",
    "dix mille deux cent soixante huit": "10268",
    "dix-sept mille trois cent soixante cinq": "17365",
    "vingt mille cent": "20100",
    "vingt-deux mille cent": "22100",
    "trente-et-un mille": "31000",
    "trente-cinq mille quatre cent": "35400",
    "quarante mille cent": "40100",
    "quarante-deux mille cinq cent": "42500",
    "quatre-vingt dix mille": "90000",
    "quatre-vingt-dix mille cent": "90100",
    "soixante et onze mille": "71000",
    "soixante quinze mille trois cent": "75300",
    "cent mille": "100000",
    "deux cent mille": "200000",
    "trois cent mille": "300000",
    "quatre cent mille": "400000",
    "cinq cent mille": "500000",
    "sept cent mille": "700000",
    "neuf cent mille": "900000",
    "cent un mille cent": "101100",
    "cent vingt-trois mille quatre cent cinquante six": "123456",
    "deux cent mille trois cents": "200300",
    "trois cent mille quatre cents": "300400",
    "quatre cent mille cinq cents": "400500",
    "cinq cent mille six cents": "500600",
    "cinq cent cinquante cinq mille cinq cent cinquante cinq": "555555",
    "soixante mille huit cents": "60800",
    "soixante-dix mille deux cents": "70200",
    "soixante-dix mille neuf cents": "70900",
    "quatre-vingt mille trois cents": "80300",
    "quatre-vingt-dix mille quatre cents": "90400",
    "cent quarante-quatre mille": "144000",
    "deux cent cinquante mille": "250000",
    "un million": "1000000",
    "un million un": "1000001",
    "un million cent": "1000100",
    "un million deux cent mille": "1200000",
    "un million deux cent cinquante mille": "1250000",
    "un million cinq cent mille": "1500000",
    "deux millions un": "2000001",
    "deux millions trois cent mille": "2300000",
    "deux millions trois cent quarante cinq mille six cent soixante sept": "2345667",
    "trois millions deux cent un": "3000201",
    "trois millions deux cent milles deux cent quatre vingt dix huit": "3200298",
    "trois millions quatre cent mille": "3400000",
    "quatre millions": "4000000",
    "trente millions cent mille": "30100000",
    "cinquante millions": "50000000",
    "cent millions": "100000000",
    "cent millions deux cent mille": "100200000",
    "deux cent millions cinq cent mille": "200500000",
    "un milliard": "1000000000",
    "un milliard cent millions": "1100000000",
    "un milliard deux cent millions trois mille quatre cent cinquante six": "1200003456",
    "deux milliards": "2000000000",
    "deux milliards cinq cents millions": "2500000000",
    "trois milliards deux cent millions": "3200000000",
    "trois milliards quatre cent millions": "3400000000",
    "trois milliards huit cents millions": "3800000000",
    "quatre milliards cinq cent millions": "4500000000",
    "cinq milliards": "5000000000",
    "un billion": "1000000000000",
    "deux billions": "2000000000000",
    "deux billions cinq cents milliards": "2500000000000",
    "14798434343": "14798434343",
    "j en veut quarante huit" : "48",






    # Pourcentages
    "il a eu zero sur 20": "0%",
    "j ai eu zero sur vingt": "0%",
    "trente et quatre pourcent": "34%",
    "quarante deux pourcent": "42%",
    "cinquante-huit %": "58%",
    "soixante pour cent": "60%",
    "quatre vingt dix pour cent": "90%",
    "quatre-vingt-dix mille cent pour cent": "90100%",
    "quatre vingt quinze pour cent": "95%",
    "cent pourcent": "100%",
    "le total est de cent pourcent": "100%",
    "trois cent quatre vingt douze %": "392%",
    "deux cent mille pourcent": "200000%",
    "vingt pour cent": "20%",
    "0.5%": "0%",
    "7.8%": "7%",
    "10.3%": "10%",
    "25.5%": "25%",
    "93 %": "93%",
    "99.9%": "99%",
    "je veut dix pourcent des pommes": "10%",
    "J'ai réussi à obtenir vingt-cinq pour cent de la note totale.": "25%",
    "Le taux de réussite est d'environ soixante-dix pour cent cette année.": "70%",
    "Il a reçu quatre-vingt-dix pour cent des voix aux élections.": "90%",
    "Cette remise correspond à dix pour cent du prix initial.": "10%",
    "Seulement quinze pour cent des participants ont répondu au sondage.": "15%",
    "On estime que cent vingt pour cent des objectifs ont été atteints.": "120%",
    "La progression est de trente-trois pour cent depuis le début de l'année.": "33%",
    "Je veux prendre soixante-dix pour cent de la part disponible.": "70%",
    "La commission prend cinq pour cent de la somme totale.": "5%",
    "Le risque est évalué à vingt pour cent dans ce cas.": "20%",
    "Ce médicament est efficace à quatre-vingt-dix-neuf pour cent.": "99%",
    "99 pour cent" : "99%",
    "Les frais représentent environ trente-cinq pour cent du budget.": "35%",
    "trente pour cent" : "30%",
    "quarente pour cent" : "40%",





    # Fractions
    "un demi": "50%",
    "la moitié": "50%",
    "moitié": "50%",
    "presque la moitié": "50%",
    "plus de la moitié": "50%",
    "je veut la moitie du lait": "50%",
    "1/2": "50%",
    "un sur deux": "50%",
    "50 sur 100": "50%",
    "un quart": "25%",
    "environ un quart": "25%",
    "1/4": "25%",
    "un sur quatre": "25%",
    "deux quart": "50%",
    "deux quarts": "50%",
    "trois quart": "75%",
    "trois quatrième": "75%",
    "trois quarts": "75%",
    "j'en ai bu les trois quarts": "75%",
    "il reste trois quart du temps": "75%",
    "3/4": "75%",
    "quatre quarts": "100%",
    "un tiers": "33%",
    "un tiers environ": "33%",
    "1/3": "33%",
    "cent sur 300": "33%",
    "deux tiers": "67%",
    "2/3": "67%",
    "4/6": "67%",
    "trois tiers": "100%",
    "3/3": "100%",
    "un cinquième": "20%",
    "1/5": "20%",
    "deux cinquièmes": "40%",
    "2/5": "40%",
    "trois cinquièmes": "60%",
    "3/5": "60%",
    "quatre cinquième": "80%",
    "quatre cinquièmes": "80%",
    "j en veut quatres cinquiemes": "80%",
    "4/5": "80%",
    "cinq cinquièmes": "100%",
    "5/5": "100%",
    "un sixième": "17%",
    "1/6": "17%",
    "trois vingtièmes": "15%",
    "un septième": "14%",
    "1/7": "14%",
    "un huitième": "12%",
    "1/8": "12%",
    "trois huitièmes": "38%",
    "5/8": "62%",
    "un neuvième": "11%",
    "1/9": "11%",
    "un dixième": "10%",
    "1/10": "10%",
    "sept dixièmes": "70%",
    "7/10": "70%",
    "neuf dixièmes": "90%",
    "9/10": "90%",
    "85 / 100": "85%",





    # Totalité et quasi-totalité
    "totalite": "100%",
    "quasi totalite": "95%",
    "quasiment tout": "95%",
    "quasiment tous": "95%",
    "quasi tous": "95%",
    "tout": "100%",
    "tous": "100%",





    # Nombres avec unités ou contextes
    "une douzaine": "12",
    "douzaine de chien": "12",
    "douzaine de pommes": "12",
    "trois douzaine": "36",
    "quatre douzaine": "48",
    "trois vingtaines": "60",
    "trois vingtaine": "60",
    "six vingtaines": "120",
    "cinq dizaines": "50",
    "trois centaines": "300",
    "dizaine de personnes": "10",
    "vingtaine d'euros": "20",
    "centaine de kilomètres": "100",
    "trois centaines de pizza" : "300",
    "millier de visiteurs": "1000",
    "plusieurs centaines": "100",
    "centaines de fois": "100",
    "environ trois cents personnes": "300",
    "les quatre cents coups": "400",
    "plusieurs milliers": "1000",
    "quelques milliers": "1000",
    "des milliers d'euros": "1000",
    "trois milles": "3000",
    "plus de mille": "1001",
    "millions d'euros": "1000000",
    "millions d'etoiles": "1000000",
    "plusieurs millions de personnes": "1000000",
    "un nombre incroyable de millions": "1000000",
    "milliards de données": "1000000000",
    "un milliard de fois": "1000000000",
    "cinq euros": "5",
    "cela coute cinquante euros": "50",
    "vingt minutes": "20",
    "huit heures": "8",
    "quarante deux ans": "42",
    "trois cent grammes": "300",
    "il y a deux pommes": "2",
    "il y a sept cent cinquante et un habitants": "751",
    "il y en a 4123": "4123",
    "Il y a dix mille deux cent soixante huit humains": "10268",
    "j ai cent quatorze de qi": "114",
    "cree moi deux dizaines de cube": "20",
    "j en veut trois trentaines": "90",





    # Nombres complexes
    "trois millions deux cents milles quatre cent quatre vingt dix huit": "3200498",
    "environ milliard deux cent mille quatre cent quatre vingt dix": "1000200490",
    "deux millions cinq cent mille": "2500000",
    "billion": "1000000000000",
    "quatre vingt mille deux cent quatre vingt dix huit" : "80298",





    # Nombres décimaux arrondis a l inferieur (on ne prend pas la partie après la virgule)
    "0.75": "0",
    "3.14": "3",
    "10.9": "10",
    "12.34": "12",
    "99.6": "99",
    "82,4" : "82",
    "quatre virgule cinq" : "4",
    "il y en a cent point quinze" : "100",



    # Expressions numériques
    "zéro zéro": "0",
    "un et un": "2",
    "deux et deux": "4",
    "dix et vingt": "30",
    "vingt et trente": "50",
    "soixante et dix": "70",
    "le nombre est douze": "12",
    "deux cent soixante quatorze": "274",
    "il y en a deux cent soixante trois": "263",
    "mille deux cent soixante trois": "1263",
    "mille vingt et un": "1021",
    
    #Chiffre negatif
    "- 14" : "-14",
    "- 20" : "-20",
    "-400%" : "-400%",
    "moins 100%" : "-100%",
    "moins quatre" : "-4",
    "moins deux septièmes" : "-29%",
    "moins deux" : "-2",





    # Phrases sans chiffres
    "nous sommes mardi": "AUCUN CHIFFRE",
    "la librairie marche": "AUCUN CHIFFRE",
    "je suis nova": "AUCUN CHIFFRE",
    "comme nous pouvons le voir": "AUCUN CHIFFRE",
}

    print("--- Résultats des Tests ---")
    failed = 0
    total = 0
    for phrase, expected in test_cases.items():
        result = text_to_understanding(phrase)
        if result != expected:
            print(f"❌ '{phrase}' → {result} (attendu: {expected})")
            failed += 1
        total += 1
    print("Accuracy de : ", str(total-failed),"/", str(total) )

# Lancer les tests
if __name__ == "__main__":
    run_tests()